apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
    project: demo-project
    source:
        repoURL: "https://github.com/jalbritt/argocd-example.git"
