apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standalone-app
  namespace: argocd
spec:
  project: demo-project
  source:
    repoURL: 'https://github.com/jalbritt/argocd-example.git'
    targetRevision: HEAD
    path: demos/standalone-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status: {}
