apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: database-kustomization
resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - database-ns.yaml
  - postgres-pv.yaml
  - postgres-pvc.yaml
