apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: database-kustomization
resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - database-ns.yaml
  - postgres-pv.yaml
  - postgres-pvc.yaml
configMapGenerator:
  - name: postgres-config
    literals:
    - POSTGRES_DB=example-db
    - POSTGRES_USER=myuser
secretGenerator:
  - name: postgres-secret
    literals:
    - POSTGRES_PASSWORD=postgrespass
    type: Opaque
eplacements:
  - source:
      kind: ConfigMap
      name: postgres-config
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=postgres].envFrom.[configMapRef.name=postgres-config].configMapRef.name
  - source:
      kind: Secret
      name: postgres-secrets
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=postgres].envFrom.[secretRef.name=postgres-secrets].secretRef.name
